INSERT INTO WORK.WORK_AUTHORITY (NAME) VALUES ('ADMIN');
INSERT INTO WORK.WORK_AUTHORITY (NAME) VALUES ('USER');
INSERT INTO WORK.WORK_AUTHORITY (NAME) VALUES ('PROVIDER');
INSERT INTO WORK.WORK_AUTHORITY (NAME) VALUES ('CUSTOMER');
INSERT INTO WORK.WORK_USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (NEXTVAL('WORK.USER_SEQ'),'mblagui', 'admin', 'Mhamed', 'Blagui', 'mhamed.blagui88@gmail.com', 1);
INSERT INTO WORK.WORK_USER_AUTHORITY (USER_ID , AUTHORITY_NAME) VALUES (1,'ADMIN');